services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: .env.production

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
